name: mandayatest
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  rxdart: ^0.27.7
  collection: ^1.17.2
  dio: ^5.3.3
  google_fonts: ^6.1.0
  intl: ^0.18.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  shimmer: ^3.0.0
  easy_splash_screen: ^1.0.4
  email_validator: ^2.1.17
  package_info_plus: ^4.2.0
  uuid: ^4.2.1
  syncfusion_flutter_datepicker: ^23.2.4
  carousel_slider: ^4.2.1
  video_player: ^2.8.1
  sliding_up_panel2: ^3.3.0+1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  draggable_scrollbar: ^0.1.0

  cupertino_icons: ^1.0.2


flutter_gen:
  line_length: 8000
  null_safety: true
  output: lib/core_module/gen

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/font/airbnbcereal/AirbnbCereal_W_Lt.otf
          weight: 300
        - asset: assets/font/airbnbcereal/AirbnbCereal_W_Bk.otf
          weight: 500
        - asset: assets/font/airbnbcereal/AirbnbCereal_W_Md.otf
        - asset: assets/font/airbnbcereal/AirbnbCereal_W_Bd.otf
          weight: 700
        - asset: assets/font/airbnbcereal/AirbnbCereal_W_XBd.otf
          weight: 800
        - asset: assets/font/airbnbcereal/AirbnbCereal_W_Blk.otf
          weight: 900

  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/svg/airbnb/
    - assets/png/
    - assets/jpg/
    - assets/jpg/where_to/
    - assets/font/
